spring.application.name=obra-do-berco-voluntarios

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/obra_do_berco_voluntarios
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=3F7xP9Lm2Qa8Vn5Kt1Rw6Yb4Hd9Zj8XpMc2As7Ef
jwt.expiration=3600000