spring.application.name=obra-do-berco-solicitacoes

server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/obra_do_berco_solicitacoes}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}