spring.application.name=obra-do-berco-eventos

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/obra_do_berco_eventos
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

