spring.application.name=obra-do-berco-gestante

server.port=8080

jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://localhost:5432/obra_do_berco_gestante
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
