spring.application.name=obra-do-berco-auth

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/obra_do_berco_auth
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh-expiration=2592000000
